// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolvTest.Api.Data.DbContexts;

namespace SolvTest.Api.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20200429135744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("SolvTest.Api.Data.Entities.MovieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<string>("PlaintextDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            ArtUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/The_Matrix_Poster.jpg/220px-The_Matrix_Poster.jpg",
                            HtmlDescription = "<p>Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.</p>",
                            PlaintextDescription = "Some judo flying nerds in VR",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            ArtUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Resident_evil_apocalypse_poster.jpg/220px-Resident_evil_apocalypse_poster.jpg",
                            HtmlDescription = "<p>A deadly virus from a secret Umbrella Corporation laboratory underneath Raccoon City is exposed to the world. Umbrella seals off the city to contain the virus, creating a ghost town where everyone trapped inside turns into a mutant zombie. Alice (Milla Jovovich), a survivor from Umbrella's secret lab, meets former Umbrella security officer Jill Valentine (Sienna Guillory) and mercenary Carlos Oliviera (Oded Fehr). Together, they search for a scientist (Jared Harris) who might be able to help.</p>",
                            PlaintextDescription = "Zombie flick with souped up chick",
                            ReleaseDate = new DateTime(2004, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil: Apocalypse"
                        },
                        new
                        {
                            Id = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            ArtUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/e/ea/Resident_Evil-_Afterlife.jpg/220px-Resident_Evil-_Afterlife.jpg",
                            HtmlDescription = "<p>In a world overrun with the walking dead, Alice (Milla Jovovich) continues her battle against Umbrella Corp., rounding up survivors along the way. Joined by an old friend, Alice and her group set out for a rumored safe haven in Los Angeles. Instead of sanctuary, they find the city overrun with zombies, and a trap about to spring.</p>",
                            PlaintextDescription = "Zombie flick with souped up chick and clones",
                            ReleaseDate = new DateTime(2010, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil: Afterlife"
                        });
                });

            modelBuilder.Entity("SolvTest.Api.Data.Entities.ShowTimeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovieShowTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieShowtimes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("436d60ac-2fd7-42f5-a8a2-0322dbbb005a"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2020, 4, 30, 9, 57, 44, 323, DateTimeKind.Local).AddTicks(9420)
                        },
                        new
                        {
                            Id = new Guid("005c1cb3-64df-4bfb-a44d-a2fc219e2e08"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2020, 5, 4, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2570)
                        },
                        new
                        {
                            Id = new Guid("7b5edc72-20cd-4dfe-a280-d9f711932319"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2020, 4, 30, 14, 57, 44, 343, DateTimeKind.Local).AddTicks(2630)
                        },
                        new
                        {
                            Id = new Guid("072898fd-81af-4ca7-ac79-7acd168ebf9f"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2020, 5, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2670)
                        },
                        new
                        {
                            Id = new Guid("05b2eba5-671e-47ae-a210-1471a033ab78"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2020, 4, 14, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2740)
                        },
                        new
                        {
                            Id = new Guid("77b075b3-5dcb-4042-8589-7aef333c8762"),
                            MovieId = new Guid("47c5f2e0-a1a7-44cb-8550-3144dc0dd79e"),
                            MovieShowTime = new DateTime(2017, 4, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2760)
                        },
                        new
                        {
                            Id = new Guid("b4be23ec-bbac-4eaa-aa36-cad40ce103e8"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2020, 4, 30, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2820)
                        },
                        new
                        {
                            Id = new Guid("18b7eb36-d5dc-4259-afbf-2978eada93e1"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2020, 5, 4, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2840)
                        },
                        new
                        {
                            Id = new Guid("822c1c41-c75a-4480-93ae-b20b63de37a0"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2020, 4, 30, 14, 57, 44, 343, DateTimeKind.Local).AddTicks(2840)
                        },
                        new
                        {
                            Id = new Guid("6748df42-bbc6-4d75-a899-73cb0d7c1db6"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2020, 5, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2850)
                        },
                        new
                        {
                            Id = new Guid("866a55ca-322e-40a9-bc3e-9f12cc299faf"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2020, 4, 14, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2860)
                        },
                        new
                        {
                            Id = new Guid("f0a7163d-3cba-47b3-b8a7-b6c9d5db6d42"),
                            MovieId = new Guid("dbe64947-77e5-4adc-9273-3160843781f1"),
                            MovieShowTime = new DateTime(2017, 4, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2870)
                        },
                        new
                        {
                            Id = new Guid("6f705186-13bd-411c-bec7-e88333171e08"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2020, 4, 30, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2880)
                        },
                        new
                        {
                            Id = new Guid("65976408-592b-4b4f-881a-87c48da4e2ba"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2020, 5, 4, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2880)
                        },
                        new
                        {
                            Id = new Guid("16cd1b84-5c1f-40e3-8544-22bf73095e70"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2020, 4, 30, 14, 57, 44, 343, DateTimeKind.Local).AddTicks(2890)
                        },
                        new
                        {
                            Id = new Guid("dd6c6c4f-dd33-4a8c-b3b7-e42e990116da"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2020, 5, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2900)
                        },
                        new
                        {
                            Id = new Guid("41ee978a-6130-487d-8848-8462b11ebc85"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2020, 4, 14, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2900)
                        },
                        new
                        {
                            Id = new Guid("cfe661ab-8d71-42e5-8f9c-a331ae4a9a8a"),
                            MovieId = new Guid("4d12e1fe-8109-4208-ae79-86c6bfb481a5"),
                            MovieShowTime = new DateTime(2017, 4, 29, 9, 57, 44, 343, DateTimeKind.Local).AddTicks(2910)
                        });
                });

            modelBuilder.Entity("SolvTest.Api.Data.Entities.ShowTimeEntity", b =>
                {
                    b.HasOne("SolvTest.Api.Data.Entities.MovieEntity", "Movie")
                        .WithMany("ShowTimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
